### ISSUE TITLE
Not all data exported when days match in time range

### ISSUE THREAD

**Issue by cbangera2** [cbangera2/CreditKarmaExtractor#2]
If the date range is for the same day but different month it will not scroll. Ex: Oct 1st - Nov 1st

**Comment by swartanian** [comment]
I also ran into it as this was my first scenario. Thank goodness I checked in the issues list!

**Comment by cbangera2** [comment]
@swartanian I didn't realize people were actually using this so didn't bother to fix it just pushed out a fix for this. If you have any other feature request let me know and I can try and add them

**Comment by swartanian** [comment]
Shoot, I just noticed the account name column is blank and I need it for context!
I added an issue:
I was able to download, however I noticed the Account Name, Labels and Notes columns are all blank. I don't care about Labels and Notes but I do need the Account Name.
It does seem to be returned in the graphql response fwiw.
